### ISSUE TITLE
db.Table()和singularTable=false会出现冲突

### ISSUE THREAD

**Issue by hb-chen** [micro-in-cn/config-server#2]
是不是去掉这个option，固定为true，或者使用db.Model()
https://github.com/micro-in-cn/config-server/blob/0bc6f3fca781cd6ba3384dde25daeea963e0ad9d/config-srv/domain/repository/gorm/options.go#L22

**Comment by Allenxuxu** [comment]
https://github.com/micro-in-cn/config-server/blob/0bc6f3fca781cd6ba3384dde25daeea963e0ad9d/config-srv/domain/repository/repository.go#L30

波哥，这边确实是写死的，这个 option 也确实应该删除。
